/**
 * Tier-to-risk mapping: how much collateral a borrower must post, as a
 * function of their A-Pass tier and subTier.
 *
 * Grounded in real sandbox data, not invented tier buckets, see
 * docs/TIER_DISTRIBUTION.md (generated by
 * backend/scripts/tier-distribution.ts against the live UAT sandbox on
 * 2026-08-02). The tiers that actually appear across 142 real A-Pass
 * records are: null/missing (26.8%), 0 (1.4%), 20 (23.2%), 50 (48.6%,
 * the highest tier observed). subTier spans null, 0, 1, 9, 10, 20, 30, 50,
 * 80 within those. This table is defined only over that observed range,
 * it is not extrapolated to a hypothetical 0-99 scale we have no evidence
 * for.
 *
 * IMPORTANT, tier is a string in the API, not the integer scale used
 * elsewhere: `query_apass`/`query_apass_list` return `tier` as a
 * numeric-looking STRING (e.g. `"50"`), per docs/CLEANVERSE_API.md, whereas
 * the Validator Compliance Rule object's `min_tier` is a documented 0-99
 * INTEGER. We have not confirmed these are the same numeric space, see
 * docs/TIER_DISTRIBUTION.md's closing note. `parseApiTier` below does the
 * string->number conversion explicitly at the boundary, so that ambiguity
 * has exactly one place to live rather than being silently assumed
 * throughout calling code.
 *
 * Design shape deliberately mirrors Cleanverse's own ComplianceRule object
 * (`min_tier` / `min_sub_tier` thresholds), see docs/CLEANVERSE_API.md's
 * Rule object section, since the pool contract will eventually mirror this
 * same table as an owner-settable on-chain mapping, and keeping the same
 * "minimum tier and subTier to qualify for a band" shape makes that port
 * mechanical rather than a redesign.
 */

/** 10_000 basis points = 100% collateralization. */
export const BPS_DENOMINATOR = 10_000;

/**
 * The most conservative ratio in the table. Used for tier 0 (the lowest
 * real tier observed) AND as the fallback for missing/unrecognized tier
 * data, they happen to share a value today, but are conceptually
 * distinct: tier 0 is a real, known-low-privilege tier, while the fallback
 * is "we don't know this borrower's tier at all, so assume the worst."
 * Kept as one named constant so tightening the fallback later (e.g. making
 * unknown strictly worse than tier 0) is a one-line change, not a hunt
 * through the table.
 */
export const SAFEST_RATIO_BPS = 15_000; // 150%

/**
 * One band: "a borrower at or above this tier AND (if tier matches exactly)
 * at or above this subTier qualifies for this collateral ratio." Bands are
 * checked most-privileged-first; the first match wins. This mirrors how a
 * Cleanverse ComplianceRule's min_tier/min_sub_tier pair works.
 */
interface RatioBand {
  minTier: number;
  minSubTier: number;
  ratioBps: number;
}

/**
 * Ordered most-privileged (lowest collateral requirement) to least.
 *
 * Reasoning, band by band:
 * - Tier 50 is the only tier observed at meaningfully high volume (48.6% of
 *   records) with a wide subTier spread (0 through 80), it's the only tier
 *   we have enough real signal in to justify going under 100% collateral,
 *   and only for its highest-subTier borrowers (subTier 80, 10.6% of all
 *   records, a real, non-trivial cohort, not a one-off).
 * - Tier 50 at low subTier (0) is kept at 110%, deliberately still
 *   over-collateralized, "highest tier" alone isn't treated as license to
 *   go under 100%; subTier within that tier is what earns it.
 * - Tiers 20 and 0 stay comfortably at or above 100% across their entire
 *   subTier range, per the "keep the lowest tiers at or above 100% until
 *   we tune" instruction, there's no band for tier 20/0 that dips below
 *   13000/15000 respectively regardless of subTier, because we have no
 *   data-driven basis yet for differentiating within those tiers by
 *   subTier the way we do for tier 50.
 */
const RATIO_BANDS: readonly RatioBand[] = [
  { minTier: 50, minSubTier: 80, ratioBps: 8_000 }, // 80%, under-collateralized, top cohort
  { minTier: 50, minSubTier: 50, ratioBps: 9_000 }, // 90%, under-collateralized
  { minTier: 50, minSubTier: 20, ratioBps: 10_000 }, // 100%, break-even
  { minTier: 50, minSubTier: 0, ratioBps: 11_000 }, // 110%
  { minTier: 20, minSubTier: 0, ratioBps: 13_000 }, // 130%
  { minTier: 0, minSubTier: 0, ratioBps: SAFEST_RATIO_BPS }, // 150%
];

// Sanity-check the table's own invariants at module load, so a future edit
// that breaks monotonicity or ordering fails immediately and loudly rather
// than silently producing a wrong ratio at runtime.
assertBandsWellFormed(RATIO_BANDS);

/**
 * Returns the required collateral ratio, in basis points (10_000 = 100%),
 * for a borrower at the given tier/subTier.
 *
 * Falls back to SAFEST_RATIO_BPS for:
 * - `tier` that is `null`, `undefined`, negative, or not a finite number
 *   (covers the ~26.8% of real sandbox records with `status`/`tier: null`
 *  , see docs/TIER_DISTRIBUTION.md). Fail closed, not "assume tier 0."
 * - a `tier` value that doesn't match any known band (i.e. below the
 *   lowest band's minTier, currently unreachable since the lowest band is
 *   minTier: 0, but guards against a future band-table edit that raises it).
 *
 * `subTier` missing/invalid is treated as `0` (the lowest real subTier),
 * not as a fallback to the safest tier-independent ratio, a known tier
 * with an unknown subTier should still get that tier's baseline band, not
 * be punished all the way back to SAFEST_RATIO_BPS.
 */
export function collateralRatioBps(
  tier: number | null | undefined,
  subTier: number | null | undefined,
): number {
  if (tier === null || tier === undefined || !Number.isFinite(tier) || tier < 0) {
    return SAFEST_RATIO_BPS;
  }

  const safeSubTier = subTier === null || subTier === undefined || !Number.isFinite(subTier) || subTier < 0 ? 0 : subTier;

  for (const band of RATIO_BANDS) {
    if (tier > band.minTier || (tier === band.minTier && safeSubTier >= band.minSubTier)) {
      return band.ratioBps;
    }
  }

  return SAFEST_RATIO_BPS;
}

/**
 * Parses the API's string `tier` field (e.g. "50") into the number
 * collateralRatioBps expects. Returns null for missing/non-numeric input,
 * callers should pass that straight through to collateralRatioBps, which
 * treats null as "fall back to the safest ratio," not as tier 0.
 *
 * This is the one place the string<->number tier ambiguity noted in this
 * file's header gets resolved, see docs/TIER_DISTRIBUTION.md.
 */
export function parseApiTier(tierRaw: string | null | undefined): number | null {
  if (tierRaw === null || tierRaw === undefined || tierRaw.trim() === "") return null;
  const parsed = Number(tierRaw);
  return Number.isFinite(parsed) ? parsed : null;
}

function assertBandsWellFormed(bands: readonly RatioBand[]): void {
  for (let i = 1; i < bands.length; i++) {
    const prev = bands[i - 1]!;
    const curr = bands[i]!;
    // Each band must be strictly less privileged than the one before it
    // (lower or equal minTier; if equal tier, lower minSubTier), and its
    // ratio must be >= the previous band's ratio (monotonic non-decreasing
    // as we walk from most- to least-privileged).
    const lessOrEquallyPrivileged =
      curr.minTier < prev.minTier || (curr.minTier === prev.minTier && curr.minSubTier < prev.minSubTier);
    if (!lessOrEquallyPrivileged) {
      throw new Error(
        `tierRatios RATIO_BANDS must be strictly ordered most- to least-privileged; ` +
          `band ${i} (tier ${curr.minTier}/${curr.minSubTier}) is not less privileged than band ${i - 1} (tier ${prev.minTier}/${prev.minSubTier})`,
      );
    }
    if (curr.ratioBps < prev.ratioBps) {
      throw new Error(
        `tierRatios RATIO_BANDS ratios must be monotonically non-decreasing as privilege decreases; ` +
          `band ${i} has ratioBps ${curr.ratioBps} < band ${i - 1}'s ${prev.ratioBps}`,
      );
    }
  }
}
